import { createContext, useContext, useState, useEffect } from "react";

type Language = "pt-BR" | "en-US";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("language");
      return (saved as Language) || "pt-BR";
    }
    return "pt-BR";
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      localStorage.setItem("language", language);
    }
  }, [language]);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
  };

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === "object" && k in value) {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return typeof value === "string" ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

const translations = {
  "pt-BR": {
    common: {
      back: "Voltar",
      save: "Salvar",
      cancel: "Cancelar",
      confirm: "Confirmar",
      edit: "Editar",
      delete: "Excluir",
      search: "Buscar",
      filter: "Filtrar",
      loading: "Carregando...",
      error: "Erro",
      success: "Sucesso",
      hello: "Olá",
    },
    home: {
      title: "Início",
      balance: "Saldo BRL",
      netWorth: "Patrimônio",
      totalInvested: "Total investido",
      quickActions: "Ações rápidas",
      recentTransactions: "Transações recentes",
      viewAll: "Ver todas",
      noTransactions: "Nenhuma transação recente",
      noActivity: "Nenhuma atividade recente",
      invest: "Investir",
    },
    pix: {
      title: "PIX",
      send: "Enviar",
      receive: "Receber",
      myKeys: "Minhas chaves",
      history: "Histórico",
      sendPix: "Enviar PIX",
      receivePix: "Receber PIX",
      recipientKey: "Chave do destinatário",
      amount: "Valor",
      description: "Descrição",
      optional: "Opcional",
      confirmSend: "Confirmar envio",
      pixSent: "PIX enviado",
      pixSentSuccess: "PIX enviado com sucesso!",
      generateQRCode: "Gerar QR Code",
      shareKey: "Compartilhar chave",
      transactionType: "Tipo",
      sent: "Enviada",
      received: "Recebida",
      insufficientBalance: "Saldo insuficiente",
      transferSent: "Transferência enviada",
      transferReceived: "Transferência recebida",
      transactions: "Transações PIX",
      noTransactions: "Nenhuma transação encontrada",
      retry: "Tentar novamente",
      errorLoading: "Erro ao carregar transações.",
    },
    stablecoin: {
      title: "StableCOIN",
      buy: "Comprar",
      sell: "Vender",
      history: "Histórico",
      trade: "Negociar",
      rate: "Taxa de conversão",
      currentRate: "Taxa atual",
      fee: "Taxa",
      wallet: "Carteira STABLE",
      youPay: "Você paga",
      youReceive: "Você receberá",
      confirmPurchase: "Confirmar compra",
      confirmSale: "Confirmar venda",
      purchaseSuccess: "Compra realizada com sucesso!",
      saleSuccess: "Venda realizada com sucesso!",
      spread: "Spread",
      spreadApplied: "Spread aplicado",
      purchaseDescription: "Compra de stable",
      saleDescription: "Venda de stable",
      balanceBRL: "Saldo BRL",
      balanceStable: "Saldo Stable",
      convertCurrency: "Converter moeda",
      convertDescription: "Compre ou venda StableCOIN com taxa competitiva",
      valueBRL: "Valor em BRL",
      valueStable: "Valor em Stable",
      buyStablecoin: "Comprar StableCOIN",
      sellStablecoin: "Vender StableCOIN",
      conversionRate: "Taxa de conversão",
      conversionHistory: "Histórico de conversões",
      allTransactions: "Todas as suas transações de StableCOIN",
      noTransactions: "Nenhuma transação encontrada",
      errorLoading: "Erro ao carregar transações.",
      retry: "Tentar novamente",
      invalidAmount: "Valor inválido",
      enterValidAmount: "Digite um valor válido para a conversão",
      errorTitle: "Erro na conversão",
      errorDescription: "Não foi possível realizar a conversão",
      processing: "Processando...",
      completed: "Concluído",
      authConversion: "Autorizar conversão",
      authDescription: "Digite sua senha para confirmar a",
    },
    investments: {
      title: "Investimentos",
      products: "Produtos",
      portfolio: "Minha carteira",
      risk: "Risco",
      low: "Baixo",
      medium: "Médio",
      high: "Alto",
      returnRate: "Retorno anual",
      liquidity: "Liquidez",
      daily: "Diária",
      monthly: "Mensal",
      maturity: "No vencimento",
      minimumInvestment: "Investimento mínimo",
      invest: "Investir",
      confirmInvestment: "Confirmar investimento",
      investmentSuccess: "Investimento realizado com sucesso!",
      totalAmount: "Valor total",
      currentValue: "Valor atual",
    },
    settings: {
      title: "Configurações",
      account: "Conta",
      accountInfo: "Informações da sua conta",
      appearance: "Aparência",
      appearanceDesc: "Personalize a interface do aplicativo",
      preferences: "Preferências",
      preferencesDesc: "Ajuste suas preferências de uso",
      security: "Segurança",
      securityDesc: "Proteja sua conta com recursos avançados",
      privacy: "Privacidade",
      privacyDesc: "Gerencie seus dados e privacidade",
      theme: "Tema",
      light: "Claro",
      dark: "Escuro",
      system: "Sistema",
      language: "Idioma",
      changePassword: "Alterar senha",
      changePasswordDesc: "Atualize sua senha de acesso",
      biometrics: "Biometria",
      biometricsDesc: "Acesso rápido com impressão digital",
      twoFactor: "Autenticação em duas etapas",
      twoFactorDesc: "Camada extra de proteção",
      privacyPolicy: "Política de privacidade",
      termsOfUse: "Termos de uso",
      logout: "Sair da conta",
      logoutConfirm: "Logout realizado",
      logoutMessage: "Até logo!",
      version: "Versão",
    },
    support: {
      title: "Suporte",
      faq: "Perguntas frequentes",
      contact: "Fale conosco",
      contactDesc: "Nossa equipe está pronta para ajudar",
      email: "E-mail",
      phone: "Telefone",
      chat: "Chat online",
    },
    register: {
      title: "Criar conta",
      fullNameQuestion: "Qual é o seu nome completo?",
      fullNameLabel: "Nome e Sobrenome",
      fullNamePlaceholder: "Seu nome completo",
      emailQuestion: "Qual é o seu e-mail?",
      emailLabel: "E-mail",
      emailPlaceholder: "nome@email.com",
      emailInvalid: "E-mail inválido. Use o formato: nome@email.com",
      phoneQuestion: "Qual é o número do seu celular?",
      phoneLabel: "Número com DDD",
      phonePlaceholder: "(00) 00000-0000",
      cpfQuestion: "Qual é o seu CPF?",
      cpfLabel: "CPF",
      cpfPlaceholder: "000.000.000-00",
      passwordQuestion: "Crie sua senha de acesso",
      passwordHint: "Apenas 6 dígitos numéricos",
      passwordLabel: "Criar senha (6 dígitos)",
      passwordPlaceholder: "••••••",
      confirmPasswordLabel: "Confirmar senha (6 dígitos)",
      confirmTitle: "Verifique suas informações",
      confirmDescription: "Após a confirmação destes dados, eles não poderão mais ser alterados.",
      confirmButton: "CONFIRMAR",
      creating: "Criando conta...",
      success: "Conta criada com sucesso!",
      successDescription: "Você já pode fazer login na sua conta.",
      errorTitle: "Erro ao criar conta",
      errorDescription: "Tente novamente mais tarde.",
      requiredField: "Campo obrigatório",
      fillName: "Por favor, informe seu nome completo.",
      invalidEmail: "E-mail inválido",
      fillEmail: "Por favor, informe um endereço de e-mail válido (exemplo: nome@email.com).",
      invalidPhone: "Telefone inválido",
      fillPhone: "Por favor, informe um telefone válido.",
      invalidCPF: "CPF inválido",
      fillCPF: "Por favor, informe um CPF válido.",
      invalidPassword: "Senha inválida",
      passwordLength: "A senha deve ter exatamente 6 dígitos numéricos.",
      passwordNumbers: "A senha deve conter apenas números.",
      passwordMismatch: "Senhas não conferem",
      passwordMatch: "Por favor, certifique-se de que as senhas são iguais.",
    },
    login: {
      title: "Bem-vindo de volta",
      cpfLabel: "CPF",
      cpfPlaceholder: "000.000.000-00",
      passwordLabel: "Senha",
      continue: "Continuar",
      noAccount: "Não tem uma conta?",
      createAccount: "Criar conta",
      invalidCPF: "CPF inválido",
      fillCPF: "Por favor, informe um CPF válido.",
      invalidPassword: "Senha inválida",
      fillPassword: "Por favor, informe sua senha de 6 dígitos.",
      errorTitle: "Erro no login",
      errorDescription: "CPF ou senha inválidos",
    },
    welcome: {
      title: "Bem-vindo ao inwista",
      subtitle: "Sua plataforma financeira completa",
      login: "Entrar",
      register: "Criar conta",
    },
    twofa: {
      title: "Autenticação",
      description: "Digite o código de 8 dígitos enviado para seu celular",
      codePlaceholder: "00000000",
      verify: "Verificar",
      verifying: "Verificando...",
      invalidCode: "Código inválido",
      fillCode: "Por favor, informe o código de 8 dígitos.",
      errorTitle: "Erro na verificação",
      errorDescription: "Código inválido ou expirado",
    },
    profile: {
      title: "Perfil",
      personalInfo: "Informações Pessoais",
      accountData: "Dados da Conta",
    },
  },
  "en-US": {
    common: {
      back: "Back",
      save: "Save",
      cancel: "Cancel",
      confirm: "Confirm",
      edit: "Edit",
      delete: "Delete",
      search: "Search",
      filter: "Filter",
      loading: "Loading...",
      error: "Error",
      success: "Success",
      hello: "Hello",
    },
    home: {
      title: "Home",
      balance: "BRL Balance",
      netWorth: "Net Worth",
      totalInvested: "Total Invested",
      quickActions: "Quick Actions",
      recentTransactions: "Recent Transactions",
      viewAll: "View All",
      noTransactions: "No recent transactions",
      noActivity: "No recent activity",
      invest: "Invest",
    },
    pix: {
      title: "PIX",
      send: "Send",
      receive: "Receive",
      myKeys: "My Keys",
      history: "History",
      sendPix: "Send PIX",
      receivePix: "Receive PIX",
      recipientKey: "Recipient Key",
      amount: "Amount",
      description: "Description",
      optional: "Optional",
      confirmSend: "Confirm Send",
      pixSent: "PIX Sent",
      pixSentSuccess: "PIX sent successfully!",
      generateQRCode: "Generate QR Code",
      shareKey: "Share Key",
      transactionType: "Type",
      sent: "Sent",
      received: "Received",
      insufficientBalance: "Insufficient balance",
      transferSent: "Transfer sent",
      transferReceived: "Transfer received",
      transactions: "PIX Transactions",
      noTransactions: "No transactions found",
      retry: "Try again",
      errorLoading: "Error loading transactions.",
    },
    stablecoin: {
      title: "StableCOIN",
      buy: "Buy",
      sell: "Sell",
      history: "History",
      trade: "Trade",
      rate: "Conversion Rate",
      currentRate: "Current Rate",
      fee: "Fee",
      wallet: "STABLE Wallet",
      youPay: "You Pay",
      youReceive: "You Will Receive",
      confirmPurchase: "Confirm Purchase",
      confirmSale: "Confirm Sale",
      purchaseSuccess: "Purchase completed successfully!",
      saleSuccess: "Sale completed successfully!",
      spread: "Spread",
      spreadApplied: "Spread Applied",
      purchaseDescription: "Stable purchase",
      saleDescription: "Stable sale",
      balanceBRL: "BRL Balance",
      balanceStable: "Stable Balance",
      convertCurrency: "Convert currency",
      convertDescription: "Buy or sell StableCOIN with competitive rates",
      valueBRL: "Amount in BRL",
      valueStable: "Amount in Stable",
      buyStablecoin: "Buy StableCOIN",
      sellStablecoin: "Sell StableCOIN",
      conversionRate: "Conversion Rate",
      conversionHistory: "Conversion history",
      allTransactions: "All your StableCOIN transactions",
      noTransactions: "No transactions found",
      errorLoading: "Error loading transactions.",
      retry: "Try again",
      invalidAmount: "Invalid amount",
      enterValidAmount: "Enter a valid amount for conversion",
      errorTitle: "Conversion error",
      errorDescription: "Unable to complete the conversion",
      processing: "Processing...",
      completed: "Completed",
      authConversion: "Authorize conversion",
      authDescription: "Enter your password to confirm the",
    },
    investments: {
      title: "Investments",
      products: "Products",
      portfolio: "My Portfolio",
      risk: "Risk",
      low: "Low",
      medium: "Medium",
      high: "High",
      returnRate: "Annual Return",
      liquidity: "Liquidity",
      daily: "Daily",
      monthly: "Monthly",
      maturity: "At Maturity",
      minimumInvestment: "Minimum Investment",
      invest: "Invest",
      confirmInvestment: "Confirm Investment",
      investmentSuccess: "Investment completed successfully!",
      totalAmount: "Total Amount",
      currentValue: "Current Value",
    },
    settings: {
      title: "Settings",
      account: "Account",
      accountInfo: "Your account information",
      appearance: "Appearance",
      appearanceDesc: "Customize the app interface",
      preferences: "Preferences",
      preferencesDesc: "Adjust your usage preferences",
      security: "Security",
      securityDesc: "Protect your account with advanced features",
      privacy: "Privacy",
      privacyDesc: "Manage your data and privacy",
      theme: "Theme",
      light: "Light",
      dark: "Dark",
      system: "System",
      language: "Language",
      changePassword: "Change Password",
      changePasswordDesc: "Update your access password",
      biometrics: "Biometrics",
      biometricsDesc: "Quick access with fingerprint",
      twoFactor: "Two-Factor Authentication",
      twoFactorDesc: "Extra layer of protection",
      privacyPolicy: "Privacy Policy",
      termsOfUse: "Terms of Use",
      logout: "Sign Out",
      logoutConfirm: "Logged out",
      logoutMessage: "See you soon!",
      version: "Version",
    },
    support: {
      title: "Support",
      faq: "Frequently Asked Questions",
      contact: "Contact Us",
      contactDesc: "Our team is ready to help",
      email: "Email",
      phone: "Phone",
      chat: "Online Chat",
    },
    register: {
      title: "Create Account",
      fullNameQuestion: "What is your full name?",
      fullNameLabel: "Full Name",
      fullNamePlaceholder: "Your full name",
      emailQuestion: "What is your email?",
      emailLabel: "Email",
      emailPlaceholder: "name@email.com",
      emailInvalid: "Invalid email. Use the format: name@email.com",
      phoneQuestion: "What is your phone number?",
      phoneLabel: "Phone Number with Area Code",
      phonePlaceholder: "(00) 00000-0000",
      cpfQuestion: "What is your CPF?",
      cpfLabel: "CPF",
      cpfPlaceholder: "000.000.000-00",
      passwordQuestion: "Create your access password",
      passwordHint: "Only 6 numeric digits",
      passwordLabel: "Create password (6 digits)",
      passwordPlaceholder: "••••••",
      confirmPasswordLabel: "Confirm password (6 digits)",
      confirmTitle: "Verify your information",
      confirmDescription: "After confirming this data, it cannot be changed.",
      confirmButton: "CONFIRM",
      creating: "Creating account...",
      success: "Account created successfully!",
      successDescription: "You can now log in to your account.",
      errorTitle: "Error creating account",
      errorDescription: "Please try again later.",
      requiredField: "Required field",
      fillName: "Please enter your full name.",
      invalidEmail: "Invalid email",
      fillEmail: "Please enter a valid email address (example: name@email.com).",
      invalidPhone: "Invalid phone",
      fillPhone: "Please enter a valid phone number.",
      invalidCPF: "Invalid CPF",
      fillCPF: "Please enter a valid CPF.",
      invalidPassword: "Invalid password",
      passwordLength: "Password must have exactly 6 numeric digits.",
      passwordNumbers: "Password must contain only numbers.",
      passwordMismatch: "Passwords do not match",
      passwordMatch: "Please make sure the passwords match.",
    },
    login: {
      title: "Welcome back",
      cpfLabel: "CPF",
      cpfPlaceholder: "000.000.000-00",
      passwordLabel: "Password",
      continue: "Continue",
      noAccount: "Don't have an account?",
      createAccount: "Create account",
      invalidCPF: "Invalid CPF",
      fillCPF: "Please enter a valid CPF.",
      invalidPassword: "Invalid password",
      fillPassword: "Please enter your 6-digit password.",
      errorTitle: "Login error",
      errorDescription: "Invalid CPF or password",
    },
    welcome: {
      title: "Welcome to inwista",
      subtitle: "Your complete financial platform",
      login: "Login",
      register: "Create account",
    },
    twofa: {
      title: "Authentication",
      description: "Enter the 8-digit code sent to your phone",
      codePlaceholder: "00000000",
      verify: "Verify",
      verifying: "Verifying...",
      invalidCode: "Invalid code",
      fillCode: "Please enter the 8-digit code.",
      errorTitle: "Verification error",
      errorDescription: "Invalid or expired code",
    },
    profile: {
      title: "Profile",
      personalInfo: "Personal Information",
      accountData: "Account Data",
    },
  },
} as const;
